CRAWL_REQUIRED_STAMINA = 1
CRAWL_USES_STAMINA = 1
CRAWL_SPEED = 1

HOP_REQUIRED_STAMINA = 21
HOP_USES_STAMINA = 2
HOP_SPEED = 3

WALK_REQUIRED_STAMINA = 41
WALK_USES_STAMINA = 2
WALK_SPEED = 4

RUN_REQUIRED_STAMINA = 61
RUN_USES_STAMINA = 4
RUN_SPEED = 6

FLY_REQUIRED_STAMINA = 81
FLY_USES_STAMINA = 4
FLY_SPEED = 8

CLAW_SIZES = ["Small", "Medium", "Big"]
